# Generated by Django 5.2.5 on 2026-01-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'permissions': [('region_create', 'Can create regions'), ('region_update', 'Can update category'), ('region_delete', 'Can delete region')]},
        ),
    ]
