# Generated by Django 5.2.5 on 2026-01-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0002_alter_region_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
