# Generated by Django 5.2.5 on 2026-01-18 17:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('region', '0004_alter_region_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(help_text='6 digits unique post id', unique=True)),
                ('post_status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('sold', 'Sold'), ('deactivated', 'Deactivated')], default='pending', max_length=11)),
                ('post_title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('posted_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('viewed', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='category.category')),
                ('max_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_usage_range', to='category.usagerange')),
                ('min_usage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='min_usage_range', to='category.usagerange')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='region.region')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalePostAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.attribute')),
                ('salepost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salepost.salepost')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('salepost', 'attribute'), name='unique_salepost_attribute')],
            },
        ),
    ]
