# Generated by Django 5.2.5 on 2026-01-18 17:45

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salepost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='salepost_image')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salepost.salepost')),
            ],
        ),
    ]
